import { useMemo, useState } from 'react'
import { BarChart3, Boxes, ChevronDown, Coffee, CreditCard, LayoutDashboard, LogOut, Menu, Package, Plus, Receipt, Search, Settings, ShoppingCart, SlidersHorizontal, TrendingUp, Users, X, RefreshCw, LockKeyhole, Inbox, AlertCircle, LoaderCircle } from 'lucide-react'

const products = [
  { id: 1, name: 'كابتشينو', category: 'القهوة', price: 55, available: true },
  { id: 2, name: 'لاتيه مثلج', category: 'المشروبات الباردة', price: 60, available: true },
  { id: 3, name: 'كرواسون لوز', category: 'المخبوزات', price: 60, available: false },
  { id: 4, name: 'كولد برو', category: 'المشروبات الباردة', price: 45, available: true },
  { id: 5, name: 'آيسد إسباني', category: 'المشروبات الباردة', price: 60, available: true },
  { id: 6, name: 'تشيز كيك', category: 'الحلويات', price: 75, available: true },
]
const nav = [
  ['الرئيسية', LayoutDashboard, 'dashboard', 'all'], ['المنتجات', Package, 'products', 'all'], ['المخزون', Boxes, 'inventory', 'admin'], ['المبيعات', CreditCard, 'sales', 'all'], ['المصروفات', Receipt, 'expenses', 'admin'], ['التقارير', BarChart3, 'reports', 'admin'], ['المستخدمون', Users, 'users', 'admin'], ['الإعدادات', Settings, 'settings', 'admin'],
]

function api(path, options = {}) {
  const token = sessionStorage.getItem('espresso_token')
  return fetch(`/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }).then(async r => { const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.message || 'تعذر إتمام الطلب'); return data })
}
function Button({ children, loading = false, variant = 'primary', ...props }) { return <button disabled={loading || props.disabled} className={`action-button ${variant}`} {...props}>{loading ? <><LoaderCircle className="spin" size={17}/> جاري التنفيذ...</> : children}</button> }
function Skeleton({ className = '' }) { return <span className={`skeleton ${className}`} aria-hidden="true" /> }
function CardSkeleton() { return <div className="stat-card skeleton-card"><Skeleton className="w-24"/><Skeleton className="w-32 h-8"/><Skeleton className="w-16"/></div> }
function TableSkeleton({ rows = 5 }) { return <div className="table-skeleton" aria-busy="true" aria-label="جاري تحميل البيانات">{Array.from({ length: rows }).map((_, i) => <div className="skeleton-row" key={i}><Skeleton/><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>)}</div> }
function ChartSkeleton() { return <div className="chart-panel skeleton-chart" aria-busy="true"><Skeleton className="w-40 h-6"/><div className="chart-bars">{[70, 45, 85, 58, 74, 42, 66].map((h, i) => <Skeleton key={i} className="bar" style={{ height: `${h}%` }}/>)}</div></div> }
function FullPageLoader({ label = 'جاري تجهيز مساحة العمل' }) { return <main className="full-loader" dir="rtl" aria-busy="true"><div className="loader-mark"><Coffee size={34}/></div><h1 className="display">Espresso &amp; Ledger</h1><p>{label}</p><div className="loader-line"><span/></div></main> }
function EmptyState({ title = 'لا توجد بيانات حتى الآن', description = 'ستظهر البيانات هنا بمجرد توفرها.' }) { return <div className="state-card"><div className="state-icon"><Inbox size={28}/></div><h3>{title}</h3><p>{description}</p></div> }
function ErrorState({ onRetry }) { return <div className="state-card error-state"><div className="state-icon"><AlertCircle size={28}/></div><h3>حدث خطأ أثناء تحميل البيانات</h3><p>تعذر الاتصال بالخادم. حاول مرة أخرى.</p><Button onClick={onRetry} variant="outline"><RefreshCw size={16}/> إعادة المحاولة</Button></div> }
function Forbidden() { return <div className="state-card forbidden"><div className="state-icon"><LockKeyhole size={28}/></div><strong>403</strong><h3>ليس لديك صلاحية للوصول إلى هذه الصفحة</h3><p>تواصل مع مدير المقهى إذا كنت تحتاج إلى صلاحية إضافية.</p></div> }

function Login({ onLogin }) {
  const [email, setEmail] = useState('admin@espresso.com'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(e) { e.preventDefault(); setError(''); setLoading(true); try { const data = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); sessionStorage.setItem('espresso_token', data.access_token || data.token || 'session'); onLogin({ name: data.user?.name || 'أحمد محمد', role: data.user?.role || 'admin' }) } catch { setError(password ? 'بيانات الدخول غير صحيحة. تحقق من البريد وكلمة المرور.' : 'أدخل كلمة المرور للاتصال بالخادم.'); setLoading(false) } }
  return <main className="login-page" dir="rtl"><section className="login-brand"><div className="brand-orbit"><Coffee size={42}/><span>Espresso</span><span>&amp; Ledger</span></div><p>إدارة المقهى ببساطة وأناقة</p></section><section className="login-form-wrap"><form onSubmit={submit} className="login-card"><span className="eyebrow">لوحة إدارة المقهى</span><h1 className="display">مرحباً بعودتك</h1><p className="muted">الرجاء إدخال بيانات الاعتماد الخاصة بك للوصول إلى سجل المقهى.</p><label>البريد الإلكتروني<input required value={email} onChange={e => setEmail(e.target.value)} type="email" placeholder="your@email.com" /></label><label>كلمة المرور<input required value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="••••••••" /></label>{error && <div className="inline-error"><AlertCircle size={16}/>{error}</div>}<Button loading={loading} type="submit">تسجيل الدخول</Button><p className="login-foot">نظام آمن لإدارة عملياتك اليومية</p></form></section></main>
}
function Sidebar({ active, setActive, user, onLogout }) { const allowed = nav.filter(([, , , access]) => access === 'all' || user.role === 'admin'); return <aside className="sidebar"><div className="sidebar-inner"><div className="sidebar-brand"><div className="brand-square"><Coffee size={19}/></div><div><b className="display">Espresso</b><small>&amp; Ledger</small></div></div><nav>{allowed.map(([label, Icon, key]) => <button key={key} onClick={() => setActive(key)} className={active === key ? 'active' : ''}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="profile"><div className="avatar">{user.name.slice(0, 1)}</div><div><b>{user.name}</b><small>{user.role === 'admin' ? 'مدير المقهى' : 'كاشير'}</small></div><button className="logout" onClick={onLogout} aria-label="تسجيل الخروج"><LogOut size={16}/></button></div></div></aside> }
function Stat({ label, value, change, tone = 'blue' }) { return <div className={`stat-card ${tone}`}><span>{label}</span><strong>{value}</strong>{change && <small><TrendingUp size={13}/> {change}</small>}</div> }
function Chart() { return <div className="chart-panel"><div className="panel-heading"><h2>أداء المبيعات</h2><div className="segmented"><span className="selected">المبيعات</span><span>الطلبات</span></div></div><div className="chart-bars">{[78, 35, 66, 91, 74, 53, 81].map((v, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${v}%` }}/><small>{['السبت','الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'][i]}</small></div>)}</div></div> }
function Dashboard() { return <div className="page-enter"><div className="page-header"><div><span className="eyebrow">نظرة اليوم</span><h1 className="display">أهلاً محمد أحمد</h1><p className="muted">إليك نظرة عامة على أداء المقهى اليوم.</p></div><div className="header-actions"><button className="filter-button">اليوم <ChevronDown size={15}/></button><Button>تصدير التقرير</Button></div></div><div className="stats-grid">{['المبيعات','المصروفات','الطلبات','المستخدمون','المخزون'].map((x, i) => <Stat key={x} label={x} value={['12,450','4,200','342','4,200','36.4'][i]} change={['+14.5%','+8.2%','+2.4%','+12.1%','0.0%'][i]} tone={i === 4 ? 'cream' : 'blue'}/>)}</div><div className="dashboard-grid"><div className="side-panels"><div className="soft-panel"><h2>الأكثر مبيعاً</h2>{['V60 Ethiopian','Flat White','Iced Matcha','Croissant (Butter)'].map((x, i) => <div className="progress-item" key={x}><div><span>{x}</span><b>{142 - i * 22}</b></div><div className="progress"><span style={{ width: `${100 - i * 18}%` }}/></div></div>)}</div><div className="alert-panel"><h2>تنبيه المخزون</h2>{['Oat Milk (Oatly)','Guatemala Beans','Paper Cups (8oz)'].map((x, i) => <div className="alert-row" key={x}><span>{x}</span><b>{i ? 'LOW' : 'CRITICAL: 2 L'}</b></div>)}</div></div><Chart/></div><div className="section-heading"><h2>أحدث الطلبات</h2><button>عرض الكل ←</button></div><TableSkeleton rows={2}/></div> }
function Cashier() { const [cart, setCart] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('الكل'); const [submitting, setSubmitting] = useState(false); const filtered = products.filter(p => (category === 'الكل' || p.category === category) && p.name.includes(query)); const total = cart.reduce((s, p) => s + p.price, 0); async function checkout() { setSubmitting(true); try { await api('/order', { method: 'POST', body: JSON.stringify({ items: cart.map(p => ({ product: p.id, quantity: 1 })) }) }); setCart([]) } catch { } finally { setSubmitting(false) } } return <div className="page-enter"><div className="page-header"><div><span className="eyebrow">نقطة البيع</span><h1 className="display">إنشاء طلب</h1><p className="muted">اختر المنتجات لإضافة طلب جديد.</p></div><Button><Plus size={17}/> طلب جديد</Button></div><div className="pos-layout"><section><div className="pos-toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="بحث عن منتج" /></div><div className="chips">{['الكل','القهوة','المشروبات الباردة','المخبوزات','الحلويات'].map(c => <button key={c} onClick={() => setCategory(c)} className={category === c ? 'selected' : ''}>{c}</button>)}</div></div><div className="product-grid">{filtered.map(p => <button key={p.id} onClick={() => p.available && setCart(c => [...c, p])} disabled={!p.available} className="product-card"><div className="product-photo"><Coffee size={31}/><span className={p.available ? 'available' : 'unavailable'}>{p.available ? 'متوفر' : 'غير متوفر'}</span></div><div className="product-info"><b>{p.name}</b><span>{p.category}</span><strong>{p.price} جنيه</strong></div></button>)}</div>{!filtered.length && <EmptyState title="لا توجد منتجات مطابقة" description="جرّب كلمة بحث مختلفة أو اختر تصنيفاً آخر."/>}</section><aside className="cart-panel"><div className="cart-heading"><h2>الطلب الحالي</h2><span>{cart.length} عناصر</span></div>{cart.length ? <div className="cart-items">{cart.map((p, i) => <div className="cart-item" key={`${p.id}-${i}`}><div><b>{p.name}</b><small>{p.price} جنيه</small></div><button onClick={() => setCart(c => c.filter((_, idx) => idx !== i))}><X size={15}/></button></div>)}</div> : <EmptyState title="السلة فارغة" description="أضف منتجات من القائمة لبدء طلب جديد."/>}<div className="cart-total"><span>الإجمالي</span><strong>{total} جنيه</strong></div><Button disabled={!cart.length} loading={submitting} onClick={checkout}>إرسال للتحضير</Button></aside></div></div> }
function SimplePage({ title, subtitle, user }) { if (user.role !== 'admin' && ['inventory','expenses','reports','users','settings'].includes(title)) return <Forbidden/>; return <div className="page-enter"><div className="page-header"><div><span className="eyebrow">Espresso &amp; Ledger</span><h1 className="display">{title}</h1><p className="muted">{subtitle}</p></div><Button><Plus size={17}/> إضافة جديد</Button></div><div className="stats-grid compact">{[1,2,3,4].map(i => <CardSkeleton key={i}/>)}</div><div className="content-panel"><div className="panel-heading"><h2>{title} بالتفصيل</h2><div className="search-box small"><Search size={15}/><span>بحث وتصفية</span></div></div><TableSkeleton rows={5}/><EmptyState title={`لا توجد ${title} حتى الآن`} description="ستظهر السجلات هنا عند توفرها من الخادم."/></div></div> }
function App() { const [user, setUser] = useState(null); const [active, setActive] = useState('dashboard'); const title = nav.find(x => x[2] === active)?.[0] || 'الرئيسية'; if (!user) return <Login onLogin={setUser}/>; return <div className="app-shell" dir="rtl"><Sidebar active={active} setActive={setActive} user={user} onLogout={() => { sessionStorage.removeItem('espresso_token'); setUser(null) }}/><main className="app-main"><header className="topbar"><button className="mobile-menu"><Menu size={20}/></button><div className="breadcrumb">Espresso &amp; Ledger <span>‹</span><b>{title}</b></div><div className="topbar-user"><ShoppingCart size={19}/><span>{user.name}</span><ChevronDown size={15}/></div></header><div className="content-wrap">{active === 'dashboard' ? <Dashboard/> : active === 'sales' && user.role !== 'admin' ? <Cashier/> : <SimplePage title={title} subtitle="إدارة بيانات المقهى واتخاذ قرارات أفضل بناءً على بيانات واضحة." user={user}/>}</div></main></div> }
export default App
